version: "3"
services:
  discord-bot:
    build: .
    volumes:
      - .:/usr/src/app
      - persist-data:/usr/src/app/persist
    environment:
      - NODE_ENV=production
    restart: unless-stopped

volumes:
  persist-data:
