version: "3.8"

services:
  discord-bot:
    image: my-discord-bot
    container_name: discord-bot
    build: .
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=your-bot-token
      - OTHER_ENV_VAR=value
    volumes:
      - ./config:/app/config # If you need persistent config storage
